{
 "title": "bootcamp-zoe-flower-birthday-notifier",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "namespace", "query": "flyt" },
   { "name": "databaseResources" },
   { "name": "databaseCompositeResources", "query": "user-birthdays-composite" },
   { "name": "objectStoreResources" },
   {
    "name": "service",
    "query": "bootcamp-zoe-flower-birthday-notifier"
   },
   { "name": "environment", "query": "production" },
   {
    "name": "deployment",
    "label": "Deployment",
    "query": {
     "query": "label_values(kube_deployment_status_replicas{namespace=\"flyt\",deployment=~\"$service.*\"}, deployment)"
    }
   },
   {
    "name": "pods",
    "label": "Pods",
    "query": {
     "query": "label_values(kube_pod_info{namespace=\"flyt\",created_by_name=~\"$service.*$deployment.*\"}, pod)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Pods Available",
   "type": "stat",
   "description": "Number of Pods reported as running without failure",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_ready{pod=~\"$pods\",namespace=\"$namespace\"})"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 4, "y": 1 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "max(rate(container_cpu_usage_seconds_total{pod=~\"$pods\", container=\"service-tool\"}[1m])) by (pod)",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "avg(irate(container_cpu_cfs_throttled_seconds_total{pod=~\"$pods\", container=\"service-tool\"}[1m]))",
     "legendFormat": "Throttled"
    }
   ]
  },
  {
   "title": "Restarts",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kube_pod_container_status_restarts_total{namespace=~\"$namespace\",pod=~\"$pods\",container=~\"service-tool\"} > 0",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Deployments",
   "type": "table",
   "description": "Number of replicas per deployment",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "kube_deployment_status_replicas{namespace=\"flyt\",deployment=~\"$service.*\"}"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(go_goroutines{kubernetes_pod_name=~\"$pods\"})",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Memory Consumption",
   "type": "graph",
   "description": "Percentage of the memory limit in use by the pods",
   "gridPos": { "h": 7, "w": 10, "x": 4, "y": 8 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "max(container_memory_working_set_bytes{pod=~\"$pods\", container=\"service-tool\"}) by (pod) / max(kube_pod_container_resource_limits{resource=\"memory\",container=\"service-tool\",pod=~\"$pods\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "File descriptors",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_open_fds{app=\"$service\",instance=~\"$pods\"}",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "External Reported Health",
   "type": "stat",
   "description": "External HTTP test to /ping endpoint every 30 seconds checking for a 2xx response",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "min(statuscake_test_up{name=\"$service\"})"
    }
   ]
  },
  {
   "title": "GC Rate",
   "type": "graph",
   "gridPos": { "h": 4, "w": 10, "x": 4, "y": 15 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(irate(go_gc_duration_seconds_count{kubernetes_pod_name=~\"$pods\", quantile!=\"1\"}[1m]))",
     "legendFormat": "Rate"
    }
   ]
  },
  {
   "title": "GC Pause Time",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 4, "y": 19 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(go_gc_duration_seconds{kubernetes_pod_name=~\"$pods\", quantile!=\"1\"}) by (quantile)",
     "legendFormat": "p{{quantile}}"
    }
   ]
  },
  {
   "title": "Network",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 19 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate (container_network_transmit_bytes_total{pod=~\"$pods\",interface=~\"eth0|ens.*\"}[1m]))",
     "legendFormat": "TX"
    },
    {
     "expr": "sum(rate (container_network_receive_bytes_total{pod=~\"$pods\",interface=~\"eth0|ens.*\"}[1m]))",
     "legendFormat": "RX"
    }
   ]
  },
  {
   "title": "Alerts",
   "type": "stat",
   "description": "Number of alerts currently firing for service",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    { "filters": "service=$service" }
   ]
  },
  {
   "title": "HTTP",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "RPS per Status Code",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 26 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "sum(rate(kong_http_status{service=~\"$namespace.$service.(http|0)|$service\"}[1m])) by (code)",
       "legendFormat": "{{code}}"
      }
     ]
    },
    {
     "title": "Response Time",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 26 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.50, sum(rate(kong_latency_bucket{type=\"upstream\", service=~\"$namespace.$service.(http|0)|$service\"}[1m])) by (le))",
       "legendFormat": "p50"
      },
      {
       "expr": "histogram_quantile(0.75, sum(rate(kong_latency_bucket{type=\"upstream\", service=~\"$namespace.$service.(http|0)|$service\"}[1m])) by (le))",
       "legendFormat": "p75"
      },
      {
       "expr": "histogram_quantile(0.90, sum(rate(kong_latency_bucket{type=\"upstream\", service=~\"$namespace.$service.(http|0)|$service\"}[1m])) by (le))",
       "legendFormat": "p90"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(kong_latency_bucket{type=\"upstream\", service=~\"$namespace.$service.(http|0)|$service\"}[1m])) by (le))",
       "legendFormat": "p99"
      }
     ]
    },
    {
     "title": "Error Percentage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 26 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "(sum(irate(kong_http_status{service=\"$namespace.$service.(http|0)\", code=~\"5.*|499\"}[1m]) or vector(0)) / sum(irate(kong_http_status{service=\"$namespace.$service.(http|0)\"}[1m]))) * 100",
       "legendFormat": "Error"
      }
     ]
    }
   ]
  },
  {
   "title": "Events Produced",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "collapsed": true,
   "panels": [
    {
     "title": "Event Emit Duration Overall",
     "type": "graph",
     "description": "Duration as percentiles to publish messages onto the event bus as reported by service",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 35 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum(rate(eventbus_duration_of_event_emitting_seconds_bucket{app=\"$service\",instance=~\"$pods\"}[1m])) by (le))",
       "legendFormat": "p50"
      },
      {
       "expr": "histogram_quantile(0.75, sum(rate(eventbus_duration_of_event_emitting_seconds_bucket{app=\"$service\",instance=~\"$pods\"}[1m])) by (le))",
       "legendFormat": "p75"
      },
      {
       "expr": "histogram_quantile(0.90, sum(rate(eventbus_duration_of_event_emitting_seconds_bucket{app=\"$service\",instance=~\"$pods\"}[1m])) by (le))",
       "legendFormat": "p90"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(eventbus_duration_of_event_emitting_seconds_bucket{app=\"$service\",instance=~\"$pods\"}[1m])) by (le))",
       "legendFormat": "p99"
      }
     ]
    },
    {
     "title": "Event Emit Duration Per Event",
     "type": "graph",
     "description": "Duration to publish events onto the event bus as reported by service",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 35 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.90, sum(rate(eventbus_duration_of_event_emitting_seconds_bucket{app=\"$service\",instance=~\"$pods\"}[1m])) by (event, le))",
       "legendFormat": "{{event}} - p90"
      }
     ]
    },
    {
     "title": "Event Rates",
     "type": "graph",
     "description": "Rate that service is producing to the event bus",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 35 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(irate(eventbus_events_producer_total{app=\"$service\",instance=~\"$pods\"}[1m])) by (event, eventbus_type)",
       "legendFormat": "Emit - {{event}} - {{eventbus_type}}"
      },
      {
       "expr": "sum(irate(eventbus_events_producer_errors_total{app=\"$service\",instance=~\"$pods\"}[1m])) by (event)",
       "legendFormat": "Error - {{event}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Events Consumed",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "collapsed": true,
   "panels": [
    {
     "title": "Event Rates",
     "type": "graph",
     "description": "Rate that service is consuming from the event bus",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 28 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(rate(eventbus_events_consumer_total{app=\"$service\",instance=~\"$pods\"}[1m])) by (event)",
       "legendFormat": "{{event}}"
      }
     ]
    },
    {
     "title": "Event Processing Duration Overall",
     "type": "graph",
     "description": "How long each event took to processes by percentile",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 28 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum(rate(eventbus_duration_of_event_processing_seconds_bucket{app=\"$service\",instance=~\"$pods\"}[1m])) by (le))",
       "legendFormat": "p50"
      },
      {
       "expr": "histogram_quantile(0.75, sum(rate(eventbus_duration_of_event_processing_seconds_bucket{app=\"$service\",instance=~\"$pods\"}[1m])) by (le))",
       "legendFormat": "p75"
      },
      {
       "expr": "histogram_quantile(0.90, sum(rate(eventbus_duration_of_event_processing_seconds_bucket{app=\"$service\",instance=~\"$pods\"}[1m])) by (le))",
       "legendFormat": "p90"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(eventbus_duration_of_event_processing_seconds_bucket{app=\"$service\",instance=~\"$pods\"}[1m])) by (le))",
       "legendFormat": "p99"
      }
     ]
    },
    {
     "title": "Consumer Group Time Lag",
     "type": "graph",
     "description": "Amount of time between message being produced and consumed",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 28 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(eventbus_consumer_lag_milliseconds_bucket{app=\"$service\",instance=~\"$pods\"}[1m])) by (event, le))",
       "legendFormat": "{{event}} - p95"
      }
     ]
    },
    {
     "title": "Event Error Rates",
     "type": "graph",
     "description": "Error rate resulting from the service consuming events",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 35 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(rate(eventbus_events_consumer_errors_total{app=\"$service\",instance=~\"$pods\"}[1m])) by (event)",
       "legendFormat": "{{event}}"
      }
     ]
    },
    {
     "title": "Event Processing Duration Per Event",
     "type": "graph",
     "description": "How long each event took to processes by event",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 35 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.75, sum(rate(eventbus_duration_of_event_processing_seconds_bucket{app=\"$service\",instance=~\"$pods\"}[1m])) by (event, le))",
       "legendFormat": "{{event}} - p75"
      }
     ]
    }
   ]
  },
  {
   "title": "Event Bus SQS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "collapsed": true,
   "panels": [
    {
     "title": "Messages in SQS Queue",
     "type": "graph",
     "description": "Number of events available for processing in the services queues",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 43 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "bootcamp-user-created",
       "dimensions": {
        "QueueName": "event-bus-28f292eefa13b4b15a8142abd6b379ff93e440305d0df91e1240825a754d11bd"
       },
       "metricName": "ApproximateNumberOfMessagesVisible",
       "namespace": "AWS/SQS",
       "period": "1m",
       "region": "eu-west-1",
       "statistics": [ "Average" ]
      }
     ]
    },
    {
     "title": "Worker pool capacity",
     "type": "graph",
     "description": "Available number of goroutines free to receive messages.",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 43 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(flyt_job_pool_capacity{app=\"$service\",instance=~\"$pods\"}) by (queue_name)",
       "legendFormat": "{{queue_name}}"
      }
     ]
    },
    {
     "title": "Queue receive rate",
     "type": "graph",
     "description": "Number of attempts to fetch messages from the queue's. Queue receive rate will be low if no or a small number of messages are being sent to the queues.",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 43 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "sum by (queue_name) (rate(flyt_queue_receives_total{app=\"$service\",instance=~\"$pods\",status=\"success\"}[1m]))",
       "legendFormat": "{{queue_name}}"
      }
     ]
    },
    {
     "title": "Messages in SQS DLQ Queue",
     "type": "graph",
     "description": "Number of events on DLQ for service",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 50 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "bootcamp-user-created",
       "dimensions": {
        "QueueName": "event-bus-dlq-28f292eefa13b4b15a8142abd6b379ff93e440305d0df91e1240825a754d11bd"
       },
       "metricName": "ApproximateNumberOfMessagesVisible",
       "namespace": "AWS/SQS",
       "period": "1m",
       "region": "eu-west-1",
       "statistics": [ "Average" ]
      }
     ]
    },
    {
     "title": "Number of jobs received",
     "type": "graph",
     "description": "Number of messages returned per attempt to fetch messages from the service queue's",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 50 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(1, sum(rate(flyt_queue_jobs_received_bucket{app=\"$service\",instance=~\"$pods\"}[1m])) by (le, queue_name))",
       "legendFormat": "{{queue_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "GRPC Client",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 },
   "collapsed": true,
   "panels": [
    {
     "title": "Requests per Status Code",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 66 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "sum(rate(grpc_client_requests_total{app=\"$service\",instance=~\"$pods\"}[1m])) by (grpc_code)",
       "legendFormat": "{{grpc_code}}"
      }
     ]
    },
    {
     "title": "Response Time",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 66 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.50, sum(rate(grpc_client_request_duration_seconds_bucket{app=\"$service\",instance=~\"$pods\"}[1m])) by (le))",
       "legendFormat": "p50"
      },
      {
       "expr": "histogram_quantile(0.75, sum(rate(grpc_client_request_duration_seconds_bucket{app=\"$service\",instance=~\"$pods\"}[1m])) by (le))",
       "legendFormat": "p75"
      },
      {
       "expr": "histogram_quantile(0.90, sum(rate(grpc_client_request_duration_seconds_bucket{app=\"$service\",instance=~\"$pods\"}[1m])) by (le))",
       "legendFormat": "p90"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(grpc_client_request_duration_seconds_bucket{app=\"$service\",instance=~\"$pods\"}[1m])) by (le))",
       "legendFormat": "p99"
      }
     ]
    },
    {
     "title": "Error Percentage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 73 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "(sum(rate(grpc_client_requests_errors_total{app=\"$service\",instance=~\"$pods\"}[1m])) or vector(0)) / sum(rate(grpc_client_requests_total{app=\"$service\",instance=~\"$pods\"}[1m])) * 100",
       "legendFormat": "Error"
      }
     ]
    },
    {
     "title": "GRPC Errors By POS",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 73 },
     "yaxes": [
      { "format": "cpm" }
     ],
     "targets": [
      {
       "expr": "sum(increase(grpc_client_requests_total{app=\"$service\", grpc_code!=\"OK\"}[1m])) by (target)",
       "legendFormat": "{{target}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Resource - Database Composite - DynamoDB - $service-$databaseCompositeResources",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 103 },
   "repeat": "databaseCompositeResources",
   "collapsed": true,
   "panels": [
    {
     "title": "Consumed Capacity",
     "type": "graph",
     "description": "Amount of CU's being consumed per minute",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 104 },
     "yaxes": [
      { "format": "opm" }
     ],
     "targets": [
      {
       "alias": "Read - {{TableName}}",
       "dimensions": {
        "TableName": "$service-composite-$databaseCompositeResources"
       },
       "metricName": "ConsumedReadCapacityUnits",
       "namespace": "AWS/DynamoDB",
       "period": "1m",
       "region": "eu-west-1",
       "statistics": [ "Sum" ]
      },
      {
       "alias": "Write - {{TableName}}",
       "dimensions": {
        "TableName": "$service-composite-$databaseCompositeResources"
       },
       "metricName": "ConsumedWriteCapacityUnits",
       "namespace": "AWS/DynamoDB",
       "period": "1m",
       "region": "eu-west-1",
       "statistics": [ "Sum" ]
      }
     ]
    },
    {
     "title": "Successful Request Latency",
     "type": "graph",
     "description": "Latency of the successful requests to DynamoDB as reported by DynamoDB. This does not take into account network latency, client side activity, etc.",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 104 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "alias": "Get Avg - {{TableName}}",
       "dimensions": {
        "Operation": "GetItem",
        "TableName": "$service-composite-$databaseCompositeResources"
       },
       "metricName": "SuccessfulRequestLatency",
       "namespace": "AWS/DynamoDB",
       "period": "1m",
       "region": "eu-west-1",
       "statistics": [ "Average" ]
      },
      {
       "alias": "Put Avg - {{TableName}}",
       "dimensions": {
        "Operation": "PutItem",
        "TableName": "$service-composite-$databaseCompositeResources"
       },
       "metricName": "SuccessfulRequestLatency",
       "namespace": "AWS/DynamoDB",
       "period": "1m",
       "region": "eu-west-1",
       "statistics": [ "Average" ]
      }
     ]
    },
    {
     "title": "TTL Deletes",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 104 },
     "yaxes": [
      { "format": "opm" }
     ],
     "targets": [
      {
       "dimensions": {
        "TableName": "$service-composite-$databaseCompositeResources"
       },
       "metricName": "TimeToLiveDeletedItemCount",
       "namespace": "AWS/DynamoDB",
       "period": "1m",
       "region": "eu-west-1",
       "statistics": [ "Sum" ]
      }
     ]
    },
    {
     "title": "Throttle Events",
     "type": "graph",
     "description": "Number of requests throttled",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 111 },
     "yaxes": [
      { "format": "opm" }
     ],
     "targets": [
      {
       "alias": "Read - {{TableName}}",
       "dimensions": {
        "TableName": "$service-composite-$databaseCompositeResources"
       },
       "metricName": "ReadThrottleEvents",
       "namespace": "AWS/DynamoDB",
       "period": "1m",
       "region": "eu-west-1",
       "statistics": [ "Sum" ]
      },
      {
       "alias": "Write - {{TableName}}",
       "dimensions": {
        "TableName": "$service-composite-$databaseCompositeResources"
       },
       "metricName": "WriteThrottleEvents",
       "namespace": "AWS/DynamoDB",
       "period": "1m",
       "region": "eu-west-1",
       "statistics": [ "Sum" ]
      }
     ]
    },
    {
     "title": "System Errors",
     "type": "graph",
     "description": "The requests to DynamoDB that generate an HTTP 500 status code. An HTTP 500 usually indicates an internal service error.",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 111 },
     "yaxes": [
      { "format": "opm" }
     ],
     "targets": [
      {
       "alias": "Put Item - {{TableName}}",
       "dimensions": {
        "Operation": "PutItem",
        "TableName": "$service-composite-$databaseCompositeResources"
       },
       "metricName": "SystemErrors",
       "namespace": "AWS/DynamoDB",
       "period": "1m",
       "region": "eu-west-1",
       "statistics": [ "Sum" ]
      },
      {
       "alias": "Delete Item - {{TableName}}",
       "dimensions": {
        "Operation": "DeleteItem",
        "TableName": "$service-composite-$databaseCompositeResources"
       },
       "metricName": "SystemErrors",
       "namespace": "AWS/DynamoDB",
       "period": "1m",
       "region": "eu-west-1",
       "statistics": [ "Sum" ]
      },
      {
       "alias": "Update Item - {{TableName}}",
       "dimensions": {
        "Operation": "UpdateItem",
        "TableName": "$service-composite-$databaseCompositeResources"
       },
       "metricName": "SystemErrors",
       "namespace": "AWS/DynamoDB",
       "period": "1m",
       "region": "eu-west-1",
       "statistics": [ "Sum" ]
      },
      {
       "alias": "Get Item - {{TableName}}",
       "dimensions": {
        "Operation": "GetItem",
        "TableName": "$service-composite-$databaseCompositeResources"
       },
       "metricName": "SystemErrors",
       "namespace": "AWS/DynamoDB",
       "period": "1m",
       "region": "eu-west-1",
       "statistics": [ "Sum" ]
      }
     ]
    },
    {
     "title": "Conditional write check failed",
     "type": "graph",
     "description": "The number of failed attempts to perform conditional writes. This includes sequencing along with any other conditional write requests",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 111 },
     "yaxes": [
      { "format": "opm" }
     ],
     "targets": [
      {
       "alias": "{{TableName}}",
       "dimensions": {
        "TableName": "$service-composite-$databaseCompositeResources"
       },
       "metricName": "ConditionalCheckFailedRequests",
       "namespace": "AWS/DynamoDB",
       "period": "1m",
       "region": "eu-west-1",
       "statistics": [ "Sum" ]
      }
     ]
    },
    {
     "title": "Indexes Consumed Capacity",
     "type": "graph",
     "description": "Amount of CU's being consumed per minute for each index",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 118 },
     "yaxes": [
      { "format": "opm" }
     ],
     "targets": [
      {
       "alias": "Read - {{GlobalSecondaryIndexName}}",
       "dimensions": {
        "GlobalSecondaryIndexName": "*",
        "TableName": "$service-$databaseResources"
       },
       "metricName": "ConsumedReadCapacityUnits",
       "namespace": "AWS/DynamoDB",
       "period": "1m",
       "region": "eu-west-1",
       "statistics": [ "Sum" ]
      },
      {
       "alias": "Write - {{GlobalSecondaryIndexName}}",
       "dimensions": {
        "GlobalSecondaryIndexName": "*",
        "TableName": "$service-$databaseResources"
       },
       "metricName": "ConsumedWriteCapacityUnits",
       "namespace": "AWS/DynamoDB",
       "period": "1m",
       "region": "eu-west-1",
       "statistics": [ "Sum" ]
      }
     ]
    },
    {
     "title": "Indexes Throttle Events",
     "type": "graph",
     "description": "Number of requests throttled per index",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 118 },
     "yaxes": [
      { "format": "opm" }
     ],
     "targets": [
      {
       "alias": "Read - {{GlobalSecondaryIndexName}}",
       "dimensions": {
        "GlobalSecondaryIndexName": "*",
        "TableName": "$service-$databaseResources"
       },
       "metricName": "ReadThrottleEvents",
       "namespace": "AWS/DynamoDB",
       "period": "1m",
       "region": "eu-west-1",
       "statistics": [ "Sum" ]
      },
      {
       "alias": "Write - {{GlobalSecondaryIndexName}}",
       "dimensions": {
        "GlobalSecondaryIndexName": "*",
        "TableName": "$service-$databaseResources"
       },
       "metricName": "WriteThrottleEvents",
       "namespace": "AWS/DynamoDB",
       "period": "1m",
       "region": "eu-west-1",
       "statistics": [ "Sum" ]
      }
     ]
    }
   ]
  }
 ]
}