// Package httpservice provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/flypay/go-kit/v4 version (devel) DO NOT EDIT.
package httpservice

const (
	ApiKeyAuthScopes = "ApiKeyAuth.Scopes"
)

// BirthdayRecord defines model for BirthdayRecord.
type BirthdayRecord struct {
	Id string `json:"id"`
}

// GetUsersWithBirthdayTodayParams defines parameters for GetUsersWithBirthdayToday.
type GetUsersWithBirthdayTodayParams struct {
	// Date date to check matching birthdays
	Date string `form:"date" json:"date"`
}
